name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build

      - name: Prepare deployment
        run: |
          # 在构建输出目录中创建 .nojekyll 文件
          touch .output/public/.nojekyll
          # 在根目录也创建 .nojekyll 文件
          touch .nojekyll
          # 列出文件以验证
          echo "Listing build output directory:"
          ls -la .output/public
          echo "Listing root directory:"
          ls -la

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .output/public
          branch: gh-pages
          clean: true
          commit-message: "Deploy: ${{ github.sha }}" 