name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build

      - name: Prepare deployment
        run: |
          # 确保构建输出目录存在
          if [ ! -d ".output/public" ]; then
            echo "Error: Build output directory .output/public does not exist"
            exit 1
          fi
          
          # 创建 .nojekyll 文件
          touch .output/public/.nojekyll
          
          # 列出文件以验证
          echo "Listing build output directory:"
          ls -la .output/public

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .output/public
          branch: gh-pages
          clean: true
          commit-message: "Deploy: ${{ github.sha }}" 